### ISSUE TITLE
how to myself do a GitHub metrics on my profile

### ISSUE THREAD

**Issue by 3dgoose** [maldron0309/maldron0309#4]

**Comment by maldron0309** [comment]
Hi @AdamOnAir  :)
I apologize for the late response. 
I'm sure you've solved it by now.
I'm following your VDL library development and cheering you on.  
I don't remember the metrics settings myself, but I think I set them up in this project: https://github.com/lowlighter/metrics I don't know if that helped :()

**Comment by 3dgoose** [comment]
Thanks for VDL !
